projects:
  genericserviceappsync:
    schemaPath: amplify/backend/api/genericserviceappsync/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: eu-west-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
